name: issue-checklist

on:
  issues:
    types: [opened,issue_comment]
  pull_request:
    types: [opened]
  project_card:
    types: [moved]
  schedule:
  - cron:  '* * * * *'


jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - uses: ben-z/actions-comment-on-issue@1.0.2
      with:
        message: "Hi:\n* Thank you for your feedback, we have received your issue, Please wait patiently for a reply.\n* In order to let us know your request as soon as possible, please provide detailed information、version or pictures.\n* If you haven't received a reply for a long time, you can subscribe to the developer's email，Mail subscription steps reference https://dolphinscheduler.apache.org/zh-cn/community/development/subscribe.html ,then send questions to dev@dolphinscheduler.apache.org."
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/translation-helper@v1.1.1
      
  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
      - name: initial labeling
        uses: andymckay/labeler@master
        with:
          add-labels: "Waiting for reply, bug"
          ignore-if-labeled: true
          remove-labels: "test"
          
  remove_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-remove-labels@v1
        if: ${{ startsWith(github.event.comment.body, '') }}
        with:
          github_token: ${{ secrets.github_token }}
          labels: bug
    

  
