name: issue-robot

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/comment-on-issue@1.0.2
      with:
        message: "Hi:\n* Thank you for your feedback, we have received your issue, Please wait patiently for a reply.\n* In order to let us know your request as soon as possible, please provide detailed information、version or pictures.\n* If you haven't received a reply for a long time, you can subscribe to the developer's email，Mail subscription steps reference https://dolphinscheduler.apache.org/zh-cn/community/development/subscribe.html ,then send questions to dev@dolphinscheduler.apache.org."
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  autoTranslate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/translation-on-issue@1.1.1

  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
      - name: initial labeling
        - uses: actions/checkout@v2
        -  uses: ./.github/actions/lable-on-issue@1.0.2
          with:
            add-labels: "Waiting for reply"
            ignore-if-labeled: true
